import "./globals.css";
import { Mulish } from "next/font/google";
import Header from "@/app/Components/Header";
import Footer from "./Components/Footer";

const mulish = Mulish({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Netflix App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
